collections:
  subpages:
    output: true
    order: 
      - YWang.md
      - YueqiuLee.md
      - Lei Li.md
      - Fangyuan Wang.md
      - ChunYu SU.md
      - Hualong Yu.md
      - Manman Qin.md
      - MianLi Wang.md
      - SiYuan Ni.md
      - Wenjing Xiang.md
      - Xingsheng Sun.md

